### ISSUE TITLE
Color control

### ISSUE THREAD

**Issue by zhangyuannie** [jozsefsallai/ask#17]
Ideally, we should respect [NO_COLOR](https://no-color.org/) to disable default color output. This can be achived by using the standard library https://deno.land/std@0.83.0/fmt/colors.ts. `inquirer` supports this by using `chalk`.

**Comment by jozsefsallai** [comment]
I'll be honest - I haven't kept up with Deno in a while, so I have a lot to catch up on. I still care about these modules and I do want to eventually update them. I'm hoping I will be able to do that by the end of the month. Thank you for the suggestion, I added it to my todo list!

**Comment by jozsefsallai** [comment]
`ask` uses [`iro`](https://github.com/jozsefsallai/iro) now to manage colors - which was also updated to support NO_COLOR.
