### ISSUE TITLE
Add marks

### ISSUE THREAD

**Issue by michailVestnik** [jozsefsallai/ask#19]
Hi!

How to replace a question mark?
To make the `Ask` better, add the ability to change the question mark. 
It would be nice to put your own signs or spinners.

Example:
```js
const answers = await ask.prompt([
  {
    name: "name",
    type: "input",
    message: "Name:",
    mark: "spinner"
  },
  {
    name: "age",
    type: "number",
    message: "Age:",
    mark: "dot"
  },
]);
```

**Comment by jozsefsallai** [comment]
Currently there's no way to make something like a spinner (or anything non-static), but you can change the prefix:

```js
const answers = await ask.prompt([
  {
    name: 'name',
    type: 'input',
    message: 'Name:',
    prefix: '>'
  }
]);
```

You can also use the `prefix` option in the global configuration, so you don't have to specify it for every single question. A `prefix` specified for individual questions will overwrite the global prefix.

Is this what you were looking for?

**Comment by michailVestnik** [comment]
Yes! That's it!
Спасибо!
