### ISSUE TITLE
No way to ask in a synchronous function

### ISSUE THREAD

**Issue by cj81499** [jozsefsallai/ask#5]
It seems you would almost always want to use ask synchronously, rather than asynchronously.

For example, in a object's constructor, you might want to ask for confirmation.

**Comment by jozsefsallai** [comment]
`ask` uses async APIs, so this is indeed not possible currently. I don't think it will ever be possible if you ask me, but I'll leave this issue open to look back on in the future (or in case someone else wants to give their input on it).

**Comment by cj81499** [comment]
Deno.ReaderSync?

https://doc.deno.land/https/github.com/denoland/deno/releases/latest/download/lib.deno.d.ts#Deno.ReaderSync

**Comment by jozsefsallai** [comment]
`ask` will undergo a fundamental rewrite in the near future and I'll make sure to provide a way to use it synchronously as well.
